package paired

import (
	"encoding/json"
	"math"
	"os"
	"reflect"
	"smp-meso/numerics"
	"smp-meso/protocol"
	"testing"
)

type parityFixture struct {
	Cases []struct {
		Request  RunRequest `json:"request"`
		Expected []struct {
			Variant
			Replicate        int       `json:"replicate"`
			InitialHash      string    `json:"initial_hash"`
			Steps            int       `json:"steps"`
			Rho              []float64 `json:"rho"`
			PointHit         *Hit      `json:"point_hit"`
			SnapshotScoreSum []float64 `json:"snapshot_score_sum"`
		} `json:"expected"`
	} `json:"cases"`
}

func fixture(t *testing.T) parityFixture {
	t.Helper()
	data, err := os.ReadFile("testdata/artifact_parity.json")
	if err != nil {
		t.Fatal(err)
	}
	var result parityFixture
	if err := json.Unmarshal(data, &result); err != nil {
		t.Fatal(err)
	}
	return result
}

func decoded(t *testing.T, array protocol.EncodedArray) []float64 {
	t.Helper()
	values, _, err := array.DecodeFloat64()
	if err != nil {
		t.Fatal(err)
	}
	return values
}

func encoded(t *testing.T, values ...float64) protocol.EncodedArray {
	t.Helper()
	array, err := protocol.EncodeFloat64(values, len(values))
	if err != nil {
		t.Fatal(err)
	}
	return array
}

// These expected trajectories were produced by the original artifact, not
// regenerated by the production implementation under test.
func TestArtifactTrajectoryParity(t *testing.T) {
	for _, item := range fixture(t).Cases {
		t.Run(item.Request.RequestID, func(t *testing.T) {
			data, err := json.Marshal(item.Request)
			if err != nil {
				t.Fatal(err)
			}
			request, err := DecodeRequest(data)
			if err != nil {
				t.Fatal(err)
			}
			result, err := Run(request)
			if err != nil {
				t.Fatal(err)
			}
			for i, expected := range item.Expected {
				path := result.Paths[i]
				if path.Variant != expected.Variant || path.Replicate != expected.Replicate ||
					path.Steps != expected.Steps ||
					!reflect.DeepEqual(path.PointHit, expected.PointHit) {
					t.Fatalf("path %d provenance or stopping differs: %+v", i, path)
				}
				// Native contraction order may change last-bit score values and
				// therefore the hash. Exact artifact hashes describe pure Go only.
				if numerics.ActiveBackend.Name() == "purego" && path.InitialHash != expected.InitialHash {
					t.Fatalf("path %d initialization differs from artifact", i)
				}
				for j, value := range decoded(t, path.Snapshots["final_rho"]) {
					if math.Abs(value-expected.Rho[j]) > 2e-12 {
						t.Fatalf("path %d rho[%d]=%g, want %g", i, j, value, expected.Rho[j])
					}
				}
				for j, value := range decoded(t, path.Snapshots["score_sum"]) {
					if math.Abs(value-expected.SnapshotScoreSum[j]) > 2e-10*math.Max(1, math.Abs(value)) {
						t.Fatalf("path %d score sum at snapshot %d differs", i, j)
					}
				}
				if path.MaxMassError > 1e-10 || path.MaxRowError > 1e-10 {
					t.Fatalf("conservation: %+v", path)
				}
				if i%len(request.Variants) != 0 && path.InitialHash != result.Paths[i-i%len(request.Variants)].InitialHash {
					t.Fatal("unpaired initial states")
				}
			}
			for _, summary := range result.Summaries {
				for _, estimate := range []Estimate{summary.Primary, summary.PointHit} {
					total := 0
					for _, count := range estimate.Counts {
						total += count
					}
					if total != len(request.Seeds) {
						t.Fatal("summary dropped a path")
					}
				}
			}
		})
	}
}

func withoutTiming(result Result) Result {
	result.Diagnostics.ElapsedSeconds = 0
	for i := range result.Paths {
		result.Paths[i].ElapsedSeconds = 0
	}
	return result
}

func TestWorkersProgressAndSeedSeparation(t *testing.T) {
	request := fixture(t).Cases[1].Request
	request.MaxSteps = 4
	request.Snapshots.RecordSteps = encoded(t, 0, 1, 4)
	request.Seeds[1].InitSeed = request.Seeds[0].InitSeed
	sequential, err := Run(request)
	if err != nil {
		t.Fatal(err)
	}
	request.Workers = 4
	events := []protocol.ProgressEvent{}
	parallel, err := RunWithProgress(request, 1, func(event protocol.ProgressEvent) { events = append(events, event) })
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(withoutTiming(sequential), withoutTiming(parallel)) {
		t.Fatal("workers or progress changed result")
	}
	heartbeats := 0
	for _, event := range events {
		if event.Event == "path_heartbeat" {
			heartbeats++
		}
	}
	if heartbeats == 0 {
		t.Fatal("missing heartbeat")
	}
	for i := 0; i < 2; i++ {
		a, b := parallel.Paths[i], parallel.Paths[i+len(request.Variants)]
		if a.InitialHash != b.InitialHash || !reflect.DeepEqual(a.Snapshots, b.Snapshots) {
			t.Fatal("process seed changed deterministic evolution")
		}
	}
	a, b := parallel.Paths[3], parallel.Paths[7]
	if a.InitialHash != b.InitialHash {
		t.Fatal("process seed changed initialization")
	}
	if reflect.DeepEqual(a.Snapshots["final_rho"], b.Snapshots["final_rho"]) {
		t.Fatal("stochastic continuation did not use process seed")
	}
}

func TestInitialAbsorptionAndSnapshotSelection(t *testing.T) {
	request := fixture(t).Cases[0].Request
	request.Dynamics.Tolerance = 3
	request.Snapshots = SnapshotsConfig{RecordSteps: encoded(t, 0, 50), FinalRho: true}
	result, err := Run(request)
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range result.Paths {
		if path.Steps != 0 || path.Category != "k1" || path.PointHit == nil || path.PointHit.Step != 0 {
			t.Fatal("initial absorption missed")
		}
		if _, exists := path.Snapshots["rho"]; exists {
			t.Fatal("unrequested rho history")
		}
		if _, exists := path.Snapshots["edge"]; exists {
			t.Fatal("unrequested edge history")
		}
		if !reflect.DeepEqual(decoded(t, path.Snapshots["steps"]), []float64{0}) {
			t.Fatal("unreached snapshots retained")
		}
	}
	request.Snapshots.RecordSteps = encoded(t)
	result, err = Run(request)
	if err != nil {
		t.Fatal(err)
	}
	if len(decoded(t, result.Paths[0].Snapshots["steps"])) != 0 {
		t.Fatal("unexpected history")
	}
}

func TestStrictRequestAndResourceValidation(t *testing.T) {
	request := fixture(t).Cases[0].Request
	for _, mutate := range []func(map[string]any){
		func(r map[string]any) { delete(r, "seeds") },
		func(r map[string]any) { r["seeds"] = nil },
		func(r map[string]any) { r["dt"] = 1 },
		func(r map[string]any) { r["snapshots"].(map[string]any)["rho"] = nil },
		func(r map[string]any) { delete(r["seeds"].([]any)[0].(map[string]any), "init_seed") },
		func(r map[string]any) { r["variants"].([]any)[0].(map[string]any)["extra"] = true },
	} {
		data, _ := json.Marshal(request)
		var raw map[string]any
		if err := json.Unmarshal(data, &raw); err != nil {
			t.Fatal(err)
		}
		mutate(raw)
		data, _ = json.Marshal(raw)
		if _, err := DecodeRequest(data); err == nil {
			t.Fatalf("accepted invalid JSON: %s", data)
		}
	}
	for name, mutate := range map[string]func(*RunRequest){
		"layer":            func(r *RunRequest) { r.Variants = []Variant{{"wedge", Deterministic}} },
		"evolution":        func(r *RunRequest) { r.Variants = []Variant{{"base", "drift"}} },
		"duplicate alias":  func(r *RunRequest) { r.Variants = []Variant{{"base", Deterministic}, {"l0", Deterministic}} },
		"replicate":        func(r *RunRequest) { r.Seeds = []Seed{{Replicate: 0}, {Replicate: 0}} },
		"steps":            func(r *RunRequest) { r.Snapshots.RecordSteps = encoded(t, 1, 0) },
		"fractional step":  func(r *RunRequest) { r.Snapshots.RecordSteps = encoded(t, .5) },
		"overflow":         func(r *RunRequest) { r.OpinionBins = math.MaxInt },
		"output budget":    func(r *RunRequest) { r.OpinionBins = 1000; r.Workers = 1 },
		"auxiliary budget": func(r *RunRequest) { r.Resolution.ScoreMax = math.MaxInt },
		"workers":          func(r *RunRequest) { r.Workers = 0 },
	} {
		t.Run(name, func(t *testing.T) {
			r := request
			mutate(&r)
			if err := r.Validate(); err == nil {
				t.Fatal("accepted invalid request")
			}
		})
	}
}
